FROM python:3.10-slim

ENV PYTHONUNBUFFERED True

#Copies code here to container image
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

#Install production dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD exec gunicorn --bind :$PORT --workers --threads 8 --timeout 0 main:app